site_name: Juno Innovations
repo_url: https://github.com/juno-fx/Orion-Documentation
theme:
  icon:
    repo: fontawesome/brands/github-alt
  logo: assets/juno.png
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - navigation.expand
    - toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      primary: black
      accent: orange

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Welcome:
      - index.md
      - using_plugins.md
      - getting_started.md
  - Using Plugins:
      - using_plugins.md
  - Software Installers:
      - software_installers.md
#  - Extensions:
#      - extensions.md
#  - Service Installers:
#      - service_installers.md
  - Bundles:
      - bundles.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/juno-fx/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/juno-innovations/about/
